import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Toaster } from "@/components/ui/toaster";
import { CartProvider } from "@/context/cart-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* NProgress Bar */}
      
        {/* Navbar */}
        <Navbar />
        {/* Context Provider */}
        <CartProvider>
          {children}
        </CartProvider>
        {/* Footer */}
        <Footer />
        {/* Toast Notifications */}
        <Toaster />
      </body>
    </html>
  );
}
